---
- hosts: all
  tasks:
    - yum:
        name: httpd
        state: present
    - service:
        name: httpd
        state: started
        enabled: yes
    - firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
