---
# tasks file for apache
- name: install httpd
  yum:
    name: "{{ web_pkg }}"
    state: present
- name: start and enable service
  service:
    name: "{{ web_svc }}"
    state: started
    enabled: yes
- name: allow port
  ansible.posix.firewalld:
    port: "{{ fir_port }}"
    state: enabled
    permanent: yes
    immediate: yes
- name: copy content
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
