---
# tasks file for yumrepo
- name: create repo for AppStream
  yum_repository:
    name: AppStream
    description: AppStream repo
    baseurl: file:///mnt/AppStream
    gpgcheck: no
    enabled: yes
- name: create repo for BaseOS
  yum_repository:
    name: BaseOS
    description: BaseOS repo
    baseurl: file:///mnt/BaseOS
    gpgcheck: no
    enabled: yes


